config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#index'

  devise_for :users, :path => 'accounts'
  resources :users, :except => [:index] do
    resources :contacts do
      resources :messages, :only => [:index, :new, :create, :show]
    end
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  before_create :send_message

private

  def send_message
    begin
      response = RestClient::Request.new(
        :method => :post,
        :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => { :Body => body,
                      :To => to,
                      :From => from }
      ).execute
    rescue RestClient::BadRequest => error
      message = JSON.parse(error.response)['message']
      errors.add(:base, message)
      false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      flash[:notice] = "Your message was sent!"
      redirect_to messages_path
    else
      render 'new'
    end
  end

  def show
    @message = Message.find(params[:id])
  end

  private

  def message_params
    params.require(:message).permit(:to, :from, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Texter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="container">
  <div id="user_nav">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>



<%= flash[:notice] %>
<%= flash[:alert] %>


<%= yield %>

</div>

</body>
</html>

app/views/messages/index.html.erb
<h1>Messages</h1>

<ul>
<% @messages.each do |message| %>
  <li><%= link_to message.id, message_path(message) %></li>
<% end %>
</ul>

<%= link_to "New message", new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<% if @message.errors.any? %>
  <p>Something went wrong:</p>
  <ul>
    <% @message.errors.full_messages.each do |message| %>
    <li><%= messsage %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @message do |f| %>
  <%= f.label :to %>
  <%= f.text_field :to %>
  <%= f.label :from %>
  <%= f.text_field :from %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.submit %>
<% end %>